apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: insights-on-prem-proxy
  namespace: insights-on-prem
spec:
  agentInstallNamespace: insights-on-prem
