apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnDeploymentConfig
metadata:
  name: insights-operator-proxy
  namespace: insights-on-prem
spec:
  agentInstallNamespace: openshift-insights
