apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: insights-operator-proxy
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
spec:
  supportedConfigs:
    - group: addon.open-cluster-management.io
      resource: addontemplates
      defaultConfig:
        name: insights-operator-proxy
    - group: addon.open-cluster-management.io
      resource: addondeploymentconfigs
      defaultConfig:
        name: insights-operator-proxy
        namespace: insights-on-prem-poc
  installStrategy:
    type: Placements
    placements:
      - name: insights-operator-proxy-spokes
        namespace: insights-on-prem-poc
        configs:
          - group: addon.open-cluster-management.io
            resource: addontemplates
            name: insights-operator-proxy
