apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-config
  namespace: openshift-insights
data:
  config.yaml: |
    dataReporting:
      uploadEndpoint: https://insights-on-prem.insights-on-prem-poc.svc.cluster.local:8443/api/ingress/v1/upload
      downloadEndpoint: https://insights-on-prem.insights-on-prem-poc.svc.cluster.local:8443/api/v2/cluster/%s/reports
      downloadEndpointTechPreview: https://insights-on-prem.insights-on-prem-poc.svc.cluster.local:8443/api/v2/cluster/%s/request/%s/report
      processingStatusEndpoint: https://insights-on-prem.insights-on-prem-poc.svc.cluster.local:8443/api/v2/cluster/%s/request/%s/status
      interval: 0h1m0s
