apiVersion: apps/v1
kind: Deployment
metadata:
  name: insights-on-prem
spec:
  replicas: 1
  template:
    metadata:
      name: insights-on-prem
      labels:
        app: insights-on-prem
    spec:
      serviceAccountName: insights-on-prem
      containers:
      - name: insights-on-prem
        image: quay.io/ccxdev/insights-on-premise-poc:latest
        command: ["sh", "-c",
          "uvicorn app.main:app --host 0.0.0.0 --port 8443 --ssl-keyfile /tls/tls.key --ssl-certfile /tls/tls.crt"]
        ports:
        - containerPort: 8443
          name: https
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        env:
        - name: POSTGRES_HOST
          value: "insights-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: insights-postgres
              key: database-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: insights-postgres
              key: database-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: insights-postgres
              key: database-name
      volumes:
      - name: tls
        secret:
          secretName: insights-on-prem-tls
      imagePullSecrets:
      - name: ccxdev-insights-on-prem-poc-pull-secret
  selector:
    matchLabels:
      app: insights-on-prem
