apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: insights-on-prem
spec:
  to:
    kind: Service
    name: insights-on-prem
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
